[package]
name = "hypergraph"
version = "0.1.0"
authors = ["rasviitanen <rasviitanen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-epoch = "0.8"
crossbeam-utils = "0.7"